import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
test('本机接口：群聊选择、来源校验、CSRF 与日历导出',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'shishi-test-')),port=14317,base=`http://127.0.0.1:${port}`;
 const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),SHISHI_DATA_DIR:dir},stdio:'pipe'});let log='';child.stderr.on('data',d=>log+=d);child.stdout.on('data',d=>log+=d);child.on('error',e=>log+=e.message);
 try{let page;for(let i=0;i<50;i++){try{page=await fetch(base);break;}catch{await new Promise(r=>setTimeout(r,100));}}assert(page,log);const cookie=page.headers.get('set-cookie').split(';')[0],token=readFileSync(join(dir,'agent-token'),'utf8');
 const browser={Cookie:cookie,Origin:base,'X-Requested-With':'shishi','Content-Type':'application/json'},agent={'X-Agent-Token':token,'Content-Type':'application/json'};
 assert(cookie.startsWith('shishi_session_'+port+'='));
 const post=(url,data,headers=browser)=>fetch(base+url,{method:'POST',headers,body:JSON.stringify(data)});
 const jobStatus=id=>fetch(base+'/api/ai/jobs/status?id='+id,{headers:{Cookie:cookie}}).then(r=>r.json());
 const readyJob=async id=>{for(let i=0;i<50;i++){const job=await jobStatus(id);if(job.state==='ready')return job;if(job.state==='failed')throw new Error(job.error);await new Promise(r=>setTimeout(r,10));}throw new Error('整理任务未暂存');};
 assert.equal((await post('/api/ai/jobs/start',{kind:'chat',input:{}},agent)).status,400);
 assert.equal((await post('/api/ai/jobs/start',{kind:'chat',input:{}},{...browser,Origin:'http://invalid'})).status,403);
 const cancelledJob=await (await post('/api/ai/jobs/start',{kind:'chat',input:{group:'手动整理验收',messages:[{id:'cancelled-source',text:'2026年10月8日14:30开会',sentAt:'2026-10-06'}]}})).json();await readyJob(cancelledJob.id);
 assert.equal((await post('/api/ai/jobs/pause',{id:cancelledJob.id})).status,200);assert.equal((await post('/api/ai/jobs/commit',{id:cancelledJob.id})).status,400);
 const otherCookie=(await fetch(base)).headers.get('set-cookie').split(';')[0];assert.equal((await fetch(base+'/api/ai/jobs/status?id='+cancelledJob.id,{headers:{Cookie:otherCookie}})).status,400);
 await post('/api/ai/jobs/cancel',{id:cancelledJob.id});assert.equal((await jobStatus(cancelledJob.id)).state,'cancelled');assert.equal((await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json()).tasks.length,0);assert.deepEqual(await (await fetch(base+'/api/sources?ids=cancelled-source',{headers:{Cookie:cookie}})).json(),[]);
 assert.equal((await post('/api/ai/config',{model:'invented'})).status,400);
 assert.equal((await post('/api/ai/config',{enabled:false,model:'deepseek-flash'})).status,200);
 assert.equal((await post('/api/ai/config',{enabled:true},agent)).status,400);
 assert.equal((await post('/api/ai/test',{})).status,400);
 const document={file:{name:'事项.txt',content:Buffer.from('2026年10月8日14:30 参加会议').toString('base64')},referenceDate:'2026-10-06'};
 assert.equal((await post('/api/files/import',document,agent)).status,400);
 assert.equal((await post('/api/files/import',document,{...browser,Origin:'http://invalid'})).status,403);
 const noKey=await post('/api/files/import',document);assert.equal(noKey.status,400);assert.match((await noKey.json()).error,/配置 DeepSeek/);
 const largeFile=await post('/api/files/import',{...document,file:{name:'大文本.txt',content:Buffer.alloc(2_100_000,65).toString('base64')}});assert.match((await largeFile.json()).error,/配置 DeepSeek/);
 const problem={title:'测试问题',description:'测试需求，不含私人信息',board:'学习',visibility:'private',constraints:{startDate:'2099-10-08',deadline:'2099-10-09',startTime:'18:00',endTime:'21:00',dailyMinutes:60,weekdays:[1,2,3,4,5,6,0]}};
 assert.equal((await post('/api/plans/create',problem,agent)).status,400);
 const created=await (await post('/api/plans/create',problem)).json();assert(created.id);
 const plansState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();assert.equal(plansState.problems.length,1);assert.equal(plansState.problems[0].visibility,'private');assert.equal(plansState.problems[0].material,undefined);assert.equal(plansState.tasks.length,0);
 assert.equal((await post('/api/plans/share',{problemId:created.id})).status,400);
 assert.equal((await fetch(base+'/api/plans/experience.json?problemId='+created.id,{headers:{Cookie:cookie}})).status,400);
 assert.equal((await fetch(base+'/api/plans/experience.json?problemId='+created.id)).status,401);
 const aiState=(await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json()).settings.ai;
 assert.equal(aiState.configured,false);assert.equal(aiState.model,'deepseek-flash');assert.equal(aiState.apiKey,undefined);
 assert.equal((await fetch(base+'/api/state')).status,401);
 assert.equal((await post('/api/settings',{nickname:'小王'},{Cookie:cookie,'Content-Type':'application/json'})).status,403);
 assert.equal((await post('/api/settings',{allDayReminderTime:'25:00'})).status,400);
 assert.equal((await post('/api/settings',{allDayReminderTime:'09:30'})).status,200);
 assert.equal((await post('/api/bridge/discover',{groups:['群 A','群 B']},agent)).status,200);
 let settings=(await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json()).settings;assert(settings.groups.every(g=>g.enabled===0));assert.equal(settings.allDayReminderTime,'09:30');
 assert.equal((await post('/api/import',{group:'群 A',messages:[]},agent)).status,400);
 await post('/api/settings',{enabledGroups:['群 A'],nickname:'小王'});
 const payload={group:'群 A',messages:[{id:'src',sender:'老师',text:'请大家明天下午3点开会',sentAt:'2026-10-06T10:00:00+08:00'}],tasks:[{title:'开会',sourceIds:['src'],dueAt:'2026-10-07T15:00:00+08:00',precision:'minute'}],summaries:[]};
 assert.equal((await post('/api/import',payload,agent)).status,200);assert.equal((await post('/api/import',{...payload,group:'群 B'},agent)).status,400);
 const state=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();assert.equal(state.tasks.length,1);assert.equal(state.tasks[0].status,'inbox');
 assert.equal((await post('/api/tasks/save',{title:'坏日期',dueAt:'2026-02-30',status:'pending'})).status,400);
 await post('/api/tasks/save',{id:state.tasks[0].id,title:'开会',dueAt:'2026-10-07T15:00:00+08:00',status:'pending',remindMinutes:15});
 const ics=await (await fetch(base+'/api/calendar.ics',{headers:{Cookie:cookie}})).text();assert(ics.includes('DTSTART:20261007T070000Z'));assert(ics.includes('TRIGGER:-PT15M'));
 await post('/api/settings',{categories:['文件']});
 const localBatch={group:'群 A',extraction:'local',messages:[{id:'local-1',text:'请明天提交文件',sender:'老师'},{id:'local-2',text:'请明天开会',sender:'老师'}]};
 assert.equal((await post('/api/import',localBatch,agent)).status,200);
 let localState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();
 const localTask=localState.tasks.find(t=>t.category==='文件');assert(localTask);assert.equal(localTask.dueAt,null);assert.equal(localState.tasks.length,2);
 await post('/api/import',localBatch,agent);localState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();assert.equal(localState.tasks.length,2);
 await post('/api/bridge/status',{state:'blocked',provider:'wxauto4'},agent);await post('/api/bridge/status',{message:'等待登录'},agent);
 localState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();assert.equal(localState.settings.bridgeStatus.provider,'wxauto4');
 const range={start:'2026-10-06',end:'2026-10-06'};
 assert.equal((await post('/api/settings',{messageDateRange:{start:'2026-10-07',end:'2026-10-06'}})).status,400);
 assert.equal((await post('/api/settings',{messageDateRange:{end:'2026-02-30'}})).status,400);
 assert.equal((await post('/api/settings',{messageDateRange:range})).status,200);
 const batch={group:'群 A',extraction:'local',messageDateRange:range,messages:[{id:'dated',sender:'老师',text:'请今天提交文件',sentAt:'2026-10-05T16:00:00Z'}]};
 assert.equal((await post('/api/import',{...batch,messageDateRange:{start:null,end:null}},agent)).status,400);
 assert.equal((await post('/api/import',{...batch,messages:[{...batch.messages[0],sentAt:null}]},agent)).status,400);
 assert.equal((await post('/api/import',{...batch,messages:[{...batch.messages[0],sentAt:'2026-10-06T16:00:00Z'}]},agent)).status,400);
 assert.equal((await post('/api/import',batch,agent)).status,200);
 const datedState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();
 assert.deepEqual(datedState.settings.messageDateRange,range);
 const count=datedState.tasks.length;
 await post('/api/settings',{messageDateRange:{start:'2026-10-05',end:'2026-10-07'}});
 assert.equal((await post('/api/import',{...batch,messageDateRange:{start:'2026-10-05',end:'2026-10-07'}},agent)).status,200);
 assert.equal((await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json()).tasks.length,count);
 const committedJob=await (await post('/api/ai/jobs/start',{kind:'chat',input:{group:'群 A',messages:[{id:'job-commit-source',text:'2026年10月6日提交文件',sentAt:'2026-10-06'}]}})).json();await readyJob(committedJob.id);await post('/api/ai/jobs/commit',{id:committedJob.id});for(let i=0;i<50&&(await jobStatus(committedJob.id)).state!=='completed';i++)await new Promise(r=>setTimeout(r,10));assert.equal((await jobStatus(committedJob.id)).state,'completed');assert.equal((await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json()).tasks.length,count+1);
 const bulkIds=[state.tasks[0].id,localTask.id];
 assert.equal((await post('/api/tasks/bulk',{ids:bulkIds,action:'delete'},agent)).status,400);
 assert.equal((await post('/api/tasks/bulk',{ids:[bulkIds[0],'missing'],action:'delete'})).status,400);
 assert.equal((await post('/api/tasks/bulk',{ids:bulkIds,action:'delete'})).status,200);
 const deletedState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();assert(deletedState.tasks.filter(t=>bulkIds.includes(t.id)).every(t=>t.status==='deleted'));
 assert(!(await (await fetch(base+'/api/calendar.ics',{headers:{Cookie:cookie}})).text()).includes('DTSTART:20261007T070000Z'));
 assert.equal((await post('/api/tasks/status',{id:bulkIds[0],status:'inbox'})).status,400);
 assert.equal((await post('/api/tasks/bulk',{ids:bulkIds,action:'restore'})).status,200);
 const restoredState=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();assert.equal(restoredState.tasks.find(t=>t.id===bulkIds[0]).status,'pending');assert.equal(restoredState.tasks.find(t=>t.id===localTask.id).status,'inbox');

 const taskId=state.tasks[0].id;
 assert.equal((await post('/api/tasks/save',{id:taskId,title:'开会',category:'会议',dueAt:'2099-10-09T15:00:00+08:00',status:'pending',deadlineAt:'2099-10-12',durationMinutes:45,project:'测试项目',tags:['测试'],repeat:'weekly'})).status,200);
 assert.equal((await post('/api/tasks/bulk',{ids:[taskId],action:'reschedule',options:{dueAt:'2099-10-10'}})).status,200);
 const enriched=(await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json()).tasks.find(t=>t.id===taskId);
 assert.equal(enriched.deadlineAt,'2099-10-12');assert.equal(enriched.durationMinutes,45);assert.equal(enriched.repeat,'weekly');
 assert.equal((await fetch(base+'/api/data/export')).status,401);
 assert.equal((await fetch(base+'/api/data/export',{headers:agent})).status,400);
 const backup=await (await fetch(base+'/api/data/export',{headers:{Cookie:cookie}})).json();
 assert(backup.tables.messages.length);assert(backup.tables.problems.length);assert(!('settings' in backup.tables));assert(!JSON.stringify(backup).includes(token));
 assert.equal((await post('/api/data/import',{backup},agent)).status,400);
 assert.equal((await post('/api/data/import',{backup},{...browser,Origin:'https://invalid'})).status,403);
 assert.equal((await (await post('/api/data/preview',{backup})).json()).tasks,0);
 assert.equal((await post('/api/data/import',{backup})).status,200);
 const backups=await (await fetch(base+'/api/data/backups',{headers:{Cookie:cookie}})).json();assert(backups.files.some(f=>f.startsWith('before-import-')));
 assert.equal((await post('/api/data/automatic-export',{name:'../agent-token'})).status,400);
 assert.equal((await post('/api/data/automatic-export',{name:backups.files[0]})).status,200);
 }finally{child.kill();await new Promise(r=>child.once('exit',r));rmSync(dir,{recursive:true,force:true});}
});
